version: '3.7'

services:
  server:
    container_name: 'socket-server'
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  
  client:
    container_name: 'web-server'
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - '9001:9001'

  # redis:
  #   container_name: 'redis-server'
  #   image: 'redis'